### ISSUE TITLE
importing PyTorchPredictor fails when no OpenVINO is available

### ISSUE THREAD

**Issue by vadimkantorov** [WiraDKP/pytorch_speaker_embedding_for_diarization#4]
```
$ cat test.py
from src.predict import PyTorchPredictor
p = PyTorchPredictor("model/configs.pth", "model/weights_best.pth")
#timestamps, speakers = p.predict("dataset/test/test.wav", plot=True)

$ python3 test.py
/miniconda/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from src.predict import PyTorchPredictor
  File "/root/convasr/diarization/pytorch_speaker_embedding_for_diarization/src/predict.py", line 13, in <module>
    from openvino.inference_engine import IECore, IENetwork
ModuleNotFoundError: No module named 'openvino'
```

In `src/predict.py` I replaced with:
```

try:
    from openvino.inference_engine import IECore, IENetwork
except:
    pass
```

**Comment by WiraDKP** [comment]
Hi @vadimkantorov 
Ah yes, Thank you for pointing that out. Can you send me a PR?
