### ISSUE TITLE
warning: overload of add_ is deprecated

### ISSUE THREAD

**Issue by martijnbentum** [WiraDKP/pytorch_speaker_embedding_for_diarization#6]
Hi WiraDKP,

Thanks for this nice diarization example. I have been trying to get it to work, however, I got this warning message:

jcopdl/optim/_ralamb.py:51: UserWarning: This overload of add_ is deprecated:
	add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
	add_(Tensor other, *, Number alpha) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:1025.)
  exp_avg.mul_(beta1).add_(1 - beta1, grad)

I saw that you also created this package (but cannot find the related github for it). I was wondering if it is possible for you to fix it?

Best,
Martijn

**Comment by martijnbentum** [comment]
Hi WiraDPK,

tqdm does not seem to play nice with multiprocessing
https://github.com/pytorch/pytorch/issues/9985

It gives the following exception during training:
for images, labels in tqdm(trainloader, desc="Train"):

Exception ignored in: <bound method _MultiProcessingDataLoaderIter.__del__ of <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x14c4042dcac8>>
Traceback (most recent call last):
  File "python3.6/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "python3.6/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/usr/lib/python3.6/multiprocessing/process.py", line 134, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process

And finally to:
OSError: [Errno 12] Cannot allocate memory

Progressbar2 does not cause any issues

Best,
Martijn
